### PR TITLE
Support sorting folders not just documents

### PR DESCRIPTION
**Pull request by sneat**
Similar to https://github.com/earlSt1/vtt-compendium-folders/pull/135 this allows Folders to maintain their sorting, both within the Compendium view and also when imported into the World. This is particularly useful for systems that have a lot of structure to their journal entries, and don't want them in alphabetical order.

The change to `alphaSortFolders` while it doesn't quite fit based on the method name etc, I couldn't see any impact to having it sort by the `sort` value if it exists. Obviously adjust as needed, but changing this method is what's needed to change the order in the Compendium view render.

### CODE REVIEW

**Comment by 69bossmustang** [comment]
This would be extremely useful for document folders that depends on chapter organization.

**Comment by earlSt1** [comment]
I've manually merged these changes into the main 09x-update branch, but the manual sorting still needs work.

**Comment by earlSt1** [comment]
Almost there, hoping to get a test version ready in a few days.

**Comment by earlSt1** [comment]
Implemented in v2.4.4

**Pull request closed without merging**
