### PR TITLE
Spanish

### PR DESCRIPTION
**Pull request by lozalojo**
Added spanish translation

### CODE REVIEW

**Comment by earlSt1** [comment]
Sorry I've not localized all areas of compendium folders. I'll make a commit shortly which will have all localizations

**Comment by lozalojo** [comment]
Do you leave this open and wait for new aditions, then?

**Comment by earlSt1** [comment]
Ok sorry for the wait, but all localizations should be added now (i forgot about a lot of areas )

**Comment by lozalojo** [comment]
Yup, if I update, the additions will be added here :-) Do not worry

**Comment by lozalojo** [comment]
Sorry, I didnt noticed you added new keys, I've translated and updated the PR

**Comment by earlSt1** [comment]
@lozalojo I'll merge this in and change the spanish deletePrompt1 to match what you put above:
"¿Está seguro de querer borrar el directorio {folderName}?" -> ¿Está seguro de querer borrar el directorio New Folder?

**Comment by lozalojo** [comment]
Great, thanks for changing the es.json file also so that I dont have to PR again!

**Pull request merged**
